apiVersion: v1
kind: Service
metadata:
  name: jenkin-service
  namespace: devops-tools
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
